Repository tazama-lf/typology-processor, pull requests merged in 2024-07, with the labels that each got.

#213 ci: sync workflows from central-workflows
  .github/workflows/bench.yaml
  .github/workflows/codacy.yml
  .github/workflows/codeql.yml
  .github/workflows/commit-message.yaml
  .github/workflows/conventional-commits.yml
  .github/workflows/dco-check.yaml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-image-scan.yaml
  .github/workflows/dockerfile-linter.yaml
  .github/workflows/dockerhub-image-build.yaml
  .github/workflows/gpg-verify.yml
  .github/workflows/linting.yaml
  .github/workflows/milestone.yaml
  .github/workflows/njsscan.yml
  .github/workflows/node.js.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yaml
  .github/workflows/terraform-security.yaml
Labels: CI/CD

#221 fix: Specify main branch for release workflow
  .github/workflows/release.yml
Labels: bug

#218 feat: Addition of SUPPRESS_ALERTS environmental variable
  .env.template
  Dockerfile
  README.md
  __tests__/unit/logic.service.test.ts
  package-lock.json
  src/config.ts
  src/logic.service.ts
Labels: enhancement

#228 feat: use MathJSON to evaluate Typology expressions
  README.md
  __tests__/unit/logic.service.test.ts
  package-lock.json
  package.json
  src/config.ts
  src/index.ts
  src/interfaces/iTypologyExpression.ts
  src/utils/evaluateTExpression.ts
Labels: enhancement

#236 refactor: From mathjson simplify wght
  README.md
  __tests__/unit/logic.service.test.ts
  src/interfaces/iTypologyExpression.ts
  src/logic.service.ts
  src/utils/evaluateTExpression.ts
Labels: refactor

#237 feat: Enhancement to the release workflow
  .github/workflows/release.yml
Labels: enhancement

#240 build: update lib versions
  package-lock.json
  package.json
Labels: build

#241 build: update dependencies
  .github/workflows/scorecard.yml
  package-lock.json
  package.json
Labels: build
